// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
import { Dynatrace, UserPrivacyOptions, DataCollectionLevel } from '@dynatrace/react-native-plugin';
import { NativeModules } from 'react-native';
// END EXTRA CODE

/**
 * @param {boolean} crashReportingOptedIn
 * @param {"Dynatrace.DTDataCollectionLevel.OFF"|"Dynatrace.DTDataCollectionLevel.USER_BEHAVIOR"|"Dynatrace.DTDataCollectionLevel.PERFORMANCE"} collectionLevel
 * @returns {Promise.<void>}
 */
export async function ApplyUserPrivacyOptions(crashReportingOptedIn, collectionLevel) {
	// BEGIN USER CODE
	let DT = NativeModules.DynatraceBridge;
    if (!DT) {
        console.warn("[Dynatrace] Dynatrace native module not found.");
        return null;
    }

	let level;
	switch (collectionLevel) {
		case "OFF":
			level = DataCollectionLevel.Off;
			break;
		case "PERFORMANCE":
			level = DataCollectionLevel.Performance;
			break;
		case "USER_BEHAVIOR":
			level = DataCollectionLevel.UserBehavior;
			break;
		default:
			console.warn("[Dynatrace] No collection level set.");
	}

	let privacyConfig = new UserPrivacyOptions(level, crashReportingOptedIn);
	Dynatrace.applyUserPrivacyOptions(privacyConfig);
	console.info(`[Dynatrace] User private options applied (crash reporting ${privacyConfig.crashReportingOptedIn}, data collection ${privacyConfig.dataCollectionLevel}`);
	// END USER CODE
}
