// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
import { Dynatrace } from '@dynatrace/react-native-plugin';
import { NativeModules } from 'react-native';
// END EXTRA CODE

/**
 * @returns {Promise.<MxObject>}
 */
export async function GetUserPrivacyOptions() {
	// BEGIN USER CODE
	function createMxObject(entity) {
        return new Promise((resolve, reject) => {
            mx.data.create({
                entity,
                callback: mxObject => resolve(mxObject),
                error: () => reject(new Error(`Could not create '${entity}' object to store device info`))
            });
        });
    }

	let DT = NativeModules.DynatraceBridge;
    if (!DT) {
        console.warn("[Dynatrace] Dynatrace native module not found.");
        return null;
    }

	let privacyOptions = await Dynatrace.getUserPrivacyOptions();
	let result = await createMxObject("Dynatrace.UserPrivacyOptions");
	
	result.set('CrashReportingOptedIn', privacyOptions.crashReportingOptedIn);
	result.set('DataCollectionLevel', privacyOptions.dataCollectionLevel.toString());
	return result;
	// END USER CODE
}
