// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
import { Dynatrace } from '@dynatrace/react-native-plugin';
import { NativeModules } from 'react-native';
// END EXTRA CODE

/**
 * @param {string} username
 * @returns {Promise.<void>}
 */
export async function IdentifyUser(username) {
	// BEGIN USER CODE
	let DT = NativeModules.DynatraceBridge;
    if (!DT) {
        console.warn("[Dynatrace] Dynatrace native module not found.");
        return;
    }
	console.info(`[Dynatrace] Identifying user as ${username}`);
	Dynatrace.identifyUser(username);
	// END USER CODE
}
