// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @returns {Promise.<void>}
 */
export async function Start() {
	// BEGIN USER CODE
	// should have already been started within theme to be initialized early,
	// but this action should be included to let the nativeDepdency be exported.
	let i = 0;
	i++;
	
	// END USER CODE
}
